const slider = document.querySelector(".slider-img");
const laptopsList = document.querySelector(".laptops-list .laptops");
const labelMenu = document.querySelector(".labelMenu");
const filterBrands = document.querySelectorAll(".secondary .browse");
const searchProducts = document.getElementById("searchProducts");
const userLoginPopup = document.querySelector(".openPopupLogin");
const modalLogin = document.querySelector(".modal-login");
const currentUser = JSON.parse(localStorage.getItem("currentUser")) || null;
const users = JSON.parse(localStorage.getItem("users")) || null;

const slides = [
  {
    id: 1,
    src: "assets/images/hero1.jpeg",
  },
  {
    id: 2,
    src: "assets/images/hero2.png",
  },
  {
    id: 3,
    src: "assets/images/hero3.jpeg",
  },
];

const laptopsArr = [
  {
    id: 1,
    src: "assets/images/asus_rog.png",
    name: "ASUS ROG Strix G18 (RTX4050)",
    price: 3419,
    brand: "ASUS",
    subtitle: "ASUS ROG / TUF",
    color: "black",
    country: "China",
    brief: "RAM: 16GB DDR5 4800MHz",
    description: [
      "Model: ASUS ROG Strix G18 (2023)",
      "-18” 165Hz WUXGA 100% DCI-P3 IPS Level ROG Nebula Display",
      "-Intel Core I7-13650HX 14 Core Overlock Processor",
      "-Nvidia GeForce RTX4050 6GB Max Performance (140Wt TGP)",
      "-16GB DDR5 4800MHz (Max 64GB) Memory",
      "-512GB M2 PCIe Gen4 NVMe Performance SSD",
      "-Dolby Vision & Dolby Atmos",
      "-Backlit Chiclet Keyboard Per-Key RGB",
      "-Intel WiFi6E (TriBand)",
    ],
  },
  {
    id: 2,
    src: "assets/images/asus_tuf.png",
    name: "ASUS Tuf (RTX4050)",
    price: 3419,
    brand: "ASUS",
    subtitle: "ASUS ROG / TUF",
    color: "black",
    country: "China",
    brief: "RAM: 16GB DDR5 4800MHz",
    description: [
      "Model: ASUS ROG Strix G18 (2023)",
      "-18” 165Hz WUXGA 100% DCI-P3 IPS Level ROG Nebula Display",
      "-Intel Core I7-13650HX 14 Core Overlock Processor",
      "-Nvidia GeForce RTX4050 6GB Max Performance (140Wt TGP)",
      "-16GB DDR5 4800MHz (Max 64GB) Memory",
      "-512GB M2 PCIe Gen4 NVMe Performance SSD",
      "-Dolby Vision & Dolby Atmos",
      "-Backlit Chiclet Keyboard Per-Key RGB",
      "-Intel WiFi6E (TriBand)",
    ],
  },
  {
    id: 3,
    src: "assets/images/asus_rog.png",
    name: "ASUS ROG Strix G18 (RTX4050)",
    price: 3419,
    brand: "ASUS",
    subtitle: "ASUS ROG / TUF",
    color: "black",
    country: "China",
    brief: "RAM: 16GB DDR5 4800MHz",
    description: [
      "Model: ASUS ROG Strix G18 (2023)",
      "-18” 165Hz WUXGA 100% DCI-P3 IPS Level ROG Nebula Display",
      "-Intel Core I7-13650HX 14 Core Overlock Processor",
      "-Nvidia GeForce RTX4050 6GB Max Performance (140Wt TGP)",
      "-16GB DDR5 4800MHz (Max 64GB) Memory",
      "-512GB M2 PCIe Gen4 NVMe Performance SSD",
      "-Dolby Vision & Dolby Atmos",
      "-Backlit Chiclet Keyboard Per-Key RGB",
      "-Intel WiFi6E (TriBand)",
    ],
  },
  {
    id: 4,
    src: "assets/images/asus_rog.png",
    name: "ASUS ROG Strix G18 (RTX4050)",
    price: 3419,
    brand: "ASUS",
    subtitle: "ASUS ROG / TUF",
    color: "black",
    country: "China",
    brief: "RAM: 16GB DDR5 4800MHz",
    description: [
      "Model: ASUS ROG Strix G18 (2023)",
      "-18” 165Hz WUXGA 100% DCI-P3 IPS Level ROG Nebula Display",
      "-Intel Core I7-13650HX 14 Core Overlock Processor",
      "-Nvidia GeForce RTX4050 6GB Max Performance (140Wt TGP)",
      "-16GB DDR5 4800MHz (Max 64GB) Memory",
      "-512GB M2 PCIe Gen4 NVMe Performance SSD",
      "-Dolby Vision & Dolby Atmos",
      "-Backlit Chiclet Keyboard Per-Key RGB",
      "-Intel WiFi6E (TriBand)",
    ],
  },
  {
    id: 5,
    src: "assets/images/msi.png",
    name: "MSI Katana 15 (RTX4070)",
    price: 3999,
    brand: "MSI",
    subtitle: "MSI GAMING",
    color: "black",
    country: "China",
    brief: "RAM: 16GB DDR5 5200Mhz",
    description: [
      "Model: MSI Katana 15",
      "-18” 165Hz WUXGA 100% DCI-P3 IPS Level ROG Nebula Display",
      "-Intel Core I7-13650HX 14 Core Overlock Processor",
      "-Nvidia GeForce RTX4050 6GB Max Performance (140Wt TGP)",
      "-16GB DDR5 4800MHz (Max 64GB) Memory",
      "-512GB M2 PCIe Gen4 NVMe Performance SSD",
      "-Dolby Vision & Dolby Atmos",
      "-Backlit Chiclet Keyboard Per-Key RGB",
      "-Intel WiFi6E (TriBand)",
    ],
  },
  {
    id: 6,
    src: "assets/images/asus_rog.png",
    name: "ASUS ROG Strix G18 (RTX4050)",
    price: 3419,
    brand: "ASUS",
    subtitle: "ASUS ROG / TUF",
    color: "black",
    country: "China",
    brief: "RAM: 16GB DDR5 4800MHz",
    description: [
      "Model: ASUS ROG Strix G18 (2023)",
      "-18” 165Hz WUXGA 100% DCI-P3 IPS Level ROG Nebula Display",
      "-Intel Core I7-13650HX 14 Core Overlock Processor",
      "-Nvidia GeForce RTX4050 6GB Max Performance (140Wt TGP)",
      "-16GB DDR5 4800MHz (Max 64GB) Memory",
      "-512GB M2 PCIe Gen4 NVMe Performance SSD",
      "-Dolby Vision & Dolby Atmos",
      "-Backlit Chiclet Keyboard Per-Key RGB",
      "-Intel WiFi6E (TriBand)",
    ],
  },
  {
    id: 7,
    src: "assets/images/asus_tuf.png",
    name: "ASUS Tuf (RTX4050)",
    price: 3419,
    brand: "ASUS",
    subtitle: "ASUS ROG / TUF",
    color: "black",
    country: "China",
    brief: "RAM: 16GB DDR5 4800MHz",
    description: [
      "Model: ASUS ROG Strix G18 (2023)",
      "-18” 165Hz WUXGA 100% DCI-P3 IPS Level ROG Nebula Display",
      "-Intel Core I7-13650HX 14 Core Overlock Processor",
      "-Nvidia GeForce RTX4050 6GB Max Performance (140Wt TGP)",
      "-16GB DDR5 4800MHz (Max 64GB) Memory",
      "-512GB M2 PCIe Gen4 NVMe Performance SSD",
      "-Dolby Vision & Dolby Atmos",
      "-Backlit Chiclet Keyboard Per-Key RGB",
      "-Intel WiFi6E (TriBand)",
    ],
  },
  {
    id: 8,
    src: "assets/images/asus_rog.png",
    name: "ASUS ROG Strix G15 (RTX4050)",
    price: 3219,
    brand: "ASUS",
    subtitle: "ASUS ROG / TUF",
    color: "black",
    country: "China",
    brief: "RAM: 16GB DDR5 4800MHz",
    description: [
      "Model: ASUS ROG Strix G18 (2023)",
      "-18” 165Hz WUXGA 100% DCI-P3 IPS Level ROG Nebula Display",
      "-Intel Core I7-13650HX 14 Core Overlock Processor",
      "-Nvidia GeForce RTX4050 6GB Max Performance (140Wt TGP)",
      "-16GB DDR5 4800MHz (Max 64GB) Memory",
      "-512GB M2 PCIe Gen4 NVMe Performance SSD",
      "-Dolby Vision & Dolby Atmos",
      "-Backlit Chiclet Keyboard Per-Key RGB",
      "-Intel WiFi6E (TriBand)",
    ],
  },
  {
    id: 9,
    src: "assets/images/asus_rog.png",
    name: "ASUS ROG Strix G18 (RTX4050)",
    price: 3419,
    brand: "ASUS",
    subtitle: "ASUS ROG / TUF",
    color: "black",
    country: "China",
    brief: "RAM: 16GB DDR5 4800MHz",
    description: [
      "Model: ASUS ROG Strix G18 (2023)",
      "-18” 165Hz WUXGA 100% DCI-P3 IPS Level ROG Nebula Display",
      "-Intel Core I7-13650HX 14 Core Overlock Processor",
      "-Nvidia GeForce RTX4050 6GB Max Performance (140Wt TGP)",
      "-16GB DDR5 4800MHz (Max 64GB) Memory",
      "-512GB M2 PCIe Gen4 NVMe Performance SSD",
      "-Dolby Vision & Dolby Atmos",
      "-Backlit Chiclet Keyboard Per-Key RGB",
      "-Intel WiFi6E (TriBand)",
    ],
  },
  {
    id: 10,
    src: "assets/images/asus_rog.png",
    name: "ASUS ROG Strix G18 (RTX4050)",
    price: 3419,
    brand: "ASUS",
    subtitle: "ASUS ROG / TUF",
    color: "black",
    country: "China",
    brief: "RAM: 16GB DDR5 4800MHz",
    description: [
      "Model: ASUS ROG Strix G18 (2023)",
      "-18” 165Hz WUXGA 100% DCI-P3 IPS Level ROG Nebula Display",
      "-Intel Core I7-13650HX 14 Core Overlock Processor",
      "-Nvidia GeForce RTX4050 6GB Max Performance (140Wt TGP)",
      "-16GB DDR5 4800MHz (Max 64GB) Memory",
      "-512GB M2 PCIe Gen4 NVMe Performance SSD",
      "-Dolby Vision & Dolby Atmos",
      "-Backlit Chiclet Keyboard Per-Key RGB",
      "-Intel WiFi6E (TriBand)",
    ],
  },
  {
    id: 11,
    src: "assets/images/asus_rog.png",
    name: "ASUS ROG Strix G18 (RTX4050)",
    price: 3419,
    brand: "ASUS",
    subtitle: "ASUS ROG / TUF",
    color: "black",
    country: "China",
    brief: "RAM: 16GB DDR5 4800MHz",
    description: [
      "Model: ASUS ROG Strix G18 (2023)",
      "-18” 165Hz WUXGA 100% DCI-P3 IPS Level ROG Nebula Display",
      "-Intel Core I7-13650HX 14 Core Overlock Processor",
      "-Nvidia GeForce RTX4050 6GB Max Performance (140Wt TGP)",
      "-16GB DDR5 4800MHz (Max 64GB) Memory",
      "-512GB M2 PCIe Gen4 NVMe Performance SSD",
      "-Dolby Vision & Dolby Atmos",
      "-Backlit Chiclet Keyboard Per-Key RGB",
      "-Intel WiFi6E (TriBand)",
    ],
  },
  {
    id: 12,
    src: "assets/images/asus_tuf.png",
    name: "ASUS Tuf (RTX4050)",
    price: 3419,
    brand: "ASUS",
    subtitle: "ASUS ROG / TUF",
    color: "black",
    country: "China",
    brief: "RAM: 16GB DDR5 4800MHz",
    description: [
      "Model: ASUS ROG Strix G18 (2023)",
      "-18” 165Hz WUXGA 100% DCI-P3 IPS Level ROG Nebula Display",
      "-Intel Core I7-13650HX 14 Core Overlock Processor",
      "-Nvidia GeForce RTX4050 6GB Max Performance (140Wt TGP)",
      "-16GB DDR5 4800MHz (Max 64GB) Memory",
      "-512GB M2 PCIe Gen4 NVMe Performance SSD",
      "-Dolby Vision & Dolby Atmos",
      "-Backlit Chiclet Keyboard Per-Key RGB",
      "-Intel WiFi6E (TriBand)",
    ],
  },
  {
    id: 13,
    src: "assets/images/asus_rog.png",
    name: "ASUS ROG Strix G18 (RTX4050)",
    price: 3419,
    brand: "ASUS",
    subtitle: "ASUS ROG / TUF",
    color: "black",
    country: "China",
    brief: "RAM: 16GB DDR5 4800MHz",
    description: [
      "Model: ASUS ROG Strix G18 (2023)",
      "-18” 165Hz WUXGA 100% DCI-P3 IPS Level ROG Nebula Display",
      "-Intel Core I7-13650HX 14 Core Overlock Processor",
      "-Nvidia GeForce RTX4050 6GB Max Performance (140Wt TGP)",
      "-16GB DDR5 4800MHz (Max 64GB) Memory",
      "-512GB M2 PCIe Gen4 NVMe Performance SSD",
      "-Dolby Vision & Dolby Atmos",
      "-Backlit Chiclet Keyboard Per-Key RGB",
      "-Intel WiFi6E (TriBand)",
    ],
  },
  {
    id: 14,
    src: "assets/images/asus_rog.png",
    name: "ASUS ROG Strix G18 (RTX4050)",
    price: 3419,
    brand: "ASUS",
    subtitle: "ASUS ROG / TUF",
    color: "black",
    country: "China",
    brief: "RAM: 16GB DDR5 4800MHz",
    description: [
      "Model: ASUS ROG Strix G18 (2023)",
      "-18” 165Hz WUXGA 100% DCI-P3 IPS Level ROG Nebula Display",
      "-Intel Core I7-13650HX 14 Core Overlock Processor",
      "-Nvidia GeForce RTX4050 6GB Max Performance (140Wt TGP)",
      "-16GB DDR5 4800MHz (Max 64GB) Memory",
      "-512GB M2 PCIe Gen4 NVMe Performance SSD",
      "-Dolby Vision & Dolby Atmos",
      "-Backlit Chiclet Keyboard Per-Key RGB",
      "-Intel WiFi6E (TriBand)",
    ],
  },
  {
    id: 15,
    src: "assets/images/ALIENWARE.png",
    name: "Alienware m18 R1 (RTX4090)",
    price: 3419,
    brand: "ALIENWARE",
    subtitle: "ALIENWARE",
    color: "black",
    country: "China",
    brief: "RAM: 16GB DDR5 4800MHz",
    description: [
      "Model: ALIENWARE (2023)",
      "-18” 165Hz WUXGA 100% DCI-P3 IPS Level ROG Nebula Display",
      "-Intel Core I7-13650HX 14 Core Overlock Processor",
      "-Nvidia GeForce RTX4050 6GB Max Performance (140Wt TGP)",
      "-16GB DDR5 4800MHz (Max 64GB) Memory",
      "-512GB M2 PCIe Gen4 NVMe Performance SSD",
      "-Dolby Vision & Dolby Atmos",
      "-Backlit Chiclet Keyboard Per-Key RGB",
      "-Intel WiFi6E (TriBand)",
    ],
  },
];

export {
  slider,
  slides,
  laptopsList,
  laptopsArr,
  labelMenu,
  filterBrands,
  searchProducts,
  userLoginPopup,
  modalLogin,
  currentUser,
  users,
};
